# Generated by Django 3.0.8 on 2020-07-09 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('persian_name', models.CharField(default='', max_length=100)),
                ('price', models.FloatField()),
                ('volume', models.FloatField(default=0.0)),
                ('update', models.DateTimeField()),
                ('trading_fee', models.FloatField(default=0.01)),
                ('state', models.BooleanField(default=True)),
                ('hour_tendency', models.IntegerField(default=0)),
                ('hour_calc', models.DateTimeField(default=django.utils.timezone.now)),
                ('hour_conf', models.IntegerField(default=0)),
                ('day_tendency', models.IntegerField(default=0)),
                ('day_calc', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_conf', models.IntegerField(default=0)),
                ('week_tendency', models.IntegerField(default=0)),
                ('week_calc', models.DateTimeField(default=django.utils.timezone.now)),
                ('week_conf', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_dir', models.CharField(default='polls/trained/?.h5', max_length=100)),
                ('i_scale', models.CharField(default='polls/trained/I_scaler.gz', max_length=100)),
                ('o_scale', models.CharField(default='polls/trained/O_scaler.gz', max_length=100)),
                ('time_frame', models.CharField(default='1H', max_length=20)),
                ('last_calc', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_size', models.IntegerField(default=24)),
                ('type', models.CharField(default='RNN', max_length=20)),
                ('unit', models.CharField(default='dollar', max_length=20)),
                ('upper', models.FloatField(default=0)),
                ('lower', models.FloatField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Material')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=1)),
                ('phone', models.CharField(default='09125459232', max_length=11)),
                ('last_mail_date', models.DateTimeField()),
                ('api_key', models.CharField(default='api_key', max_length=100)),
                ('secret_key', models.CharField(default='secret_key', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('start_asset', models.FloatField(default=0)),
                ('simulated_asset', models.FloatField(default=0)),
                ('real_mat_asset', models.FloatField(default=0)),
                ('real_budget', models.FloatField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('asset_chart_file', models.CharField(default='polls/chart/?.txt', max_length=100)),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Predictor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='polls.User')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='buy', max_length=3)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('real', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('budget', models.FloatField(default=0)),
                ('mat_amount', models.FloatField(default=0)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Trader')),
            ],
        ),
    ]
